"""Add financial transactions

Revision ID: 6859b429b07c
Revises: 88f1b77c6190
Create Date: 2026-07-12 12:45:35.335163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6859b429b07c'
down_revision: Union[str, None] = '88f1b77c6190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_transaction',
    sa.Column('financial_transaction_id', sa.Integer(), nullable=False),
    sa.Column('source_account', sa.String(length=100), nullable=False),
    sa.Column('destination_account', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('case_master_id', sa.Integer(), nullable=True),
    sa.Column('accused_master_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accused_master_id'], ['accused_master.accused_master_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_master_id'], ['case_master.case_master_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('financial_transaction_id')
    )
    op.create_index(op.f('ix_financial_transaction_accused_master_id'), 'financial_transaction', ['accused_master_id'], unique=False)
    op.create_index(op.f('ix_financial_transaction_case_master_id'), 'financial_transaction', ['case_master_id'], unique=False)
    op.create_index(op.f('ix_financial_transaction_destination_account'), 'financial_transaction', ['destination_account'], unique=False)
    op.create_index(op.f('ix_financial_transaction_source_account'), 'financial_transaction', ['source_account'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_transaction_source_account'), table_name='financial_transaction')
    op.drop_index(op.f('ix_financial_transaction_destination_account'), table_name='financial_transaction')
    op.drop_index(op.f('ix_financial_transaction_case_master_id'), table_name='financial_transaction')
    op.drop_index(op.f('ix_financial_transaction_accused_master_id'), table_name='financial_transaction')
    op.drop_table('financial_transaction')
    # ### end Alembic commands ###
