"""Initial migration

Revision ID: 88f1b77c6190
Revises: None
Create Date: 2026-07-12 12:42:05.772982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f1b77c6190'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_type',
    sa.Column('crime_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('crime_type_id')
    )
    op.create_index(op.f('ix_crime_type_name'), 'crime_type', ['name'], unique=True)
    op.create_table('police_station',
    sa.Column('police_station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('police_station_id')
    )
    op.create_index(op.f('ix_police_station_district'), 'police_station', ['district'], unique=False)
    op.create_index(op.f('ix_police_station_name'), 'police_station', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('case_master',
    sa.Column('case_master_id', sa.Integer(), nullable=False),
    sa.Column('crime_no', sa.String(length=50), nullable=False),
    sa.Column('case_no', sa.String(length=50), nullable=True),
    sa.Column('crime_registered_date', sa.Date(), nullable=False),
    sa.Column('police_station_id', sa.Integer(), nullable=True),
    sa.Column('crime_type_id', sa.Integer(), nullable=True),
    sa.Column('police_person_id', sa.Integer(), nullable=True),
    sa.Column('case_category_id', sa.Integer(), nullable=True),
    sa.Column('gravity_offence_id', sa.Integer(), nullable=True),
    sa.Column('crime_major_head_id', sa.Integer(), nullable=True),
    sa.Column('crime_minor_head_id', sa.Integer(), nullable=True),
    sa.Column('case_status_id', sa.Integer(), nullable=True),
    sa.Column('court_id', sa.Integer(), nullable=True),
    sa.Column('incident_from_date', sa.DateTime(), nullable=True),
    sa.Column('incident_to_date', sa.DateTime(), nullable=True),
    sa.Column('info_received_ps_date', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('brief_facts', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crime_type_id'], ['crime_type.crime_type_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['police_station_id'], ['police_station.police_station_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('case_master_id')
    )
    op.create_index(op.f('ix_case_master_case_no'), 'case_master', ['case_no'], unique=False)
    op.create_index(op.f('ix_case_master_crime_no'), 'case_master', ['crime_no'], unique=True)
    op.create_index(op.f('ix_case_master_crime_type_id'), 'case_master', ['crime_type_id'], unique=False)
    op.create_index(op.f('ix_case_master_police_station_id'), 'case_master', ['police_station_id'], unique=False)
    op.create_table('accused_master',
    sa.Column('accused_master_id', sa.Integer(), nullable=False),
    sa.Column('case_master_id', sa.Integer(), nullable=False),
    sa.Column('accused_name', sa.String(length=255), nullable=False),
    sa.Column('age_year', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['case_master_id'], ['case_master.case_master_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('accused_master_id')
    )
    op.create_index(op.f('ix_accused_master_accused_name'), 'accused_master', ['accused_name'], unique=False)
    op.create_index(op.f('ix_accused_master_case_master_id'), 'accused_master', ['case_master_id'], unique=False)
    op.create_index(op.f('ix_accused_master_person_id'), 'accused_master', ['person_id'], unique=False)
    op.create_table('victim_master',
    sa.Column('victim_master_id', sa.Integer(), nullable=False),
    sa.Column('case_master_id', sa.Integer(), nullable=False),
    sa.Column('victim_name', sa.String(length=255), nullable=False),
    sa.Column('age_year', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('victim_police', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['case_master_id'], ['case_master.case_master_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('victim_master_id')
    )
    op.create_index(op.f('ix_victim_master_case_master_id'), 'victim_master', ['case_master_id'], unique=False)
    op.create_index(op.f('ix_victim_master_victim_name'), 'victim_master', ['victim_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_victim_master_victim_name'), table_name='victim_master')
    op.drop_index(op.f('ix_victim_master_case_master_id'), table_name='victim_master')
    op.drop_table('victim_master')
    op.drop_index(op.f('ix_accused_master_person_id'), table_name='accused_master')
    op.drop_index(op.f('ix_accused_master_case_master_id'), table_name='accused_master')
    op.drop_index(op.f('ix_accused_master_accused_name'), table_name='accused_master')
    op.drop_table('accused_master')
    op.drop_index(op.f('ix_case_master_police_station_id'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_crime_type_id'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_crime_no'), table_name='case_master')
    op.drop_index(op.f('ix_case_master_case_no'), table_name='case_master')
    op.drop_table('case_master')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_police_station_name'), table_name='police_station')
    op.drop_index(op.f('ix_police_station_district'), table_name='police_station')
    op.drop_table('police_station')
    op.drop_index(op.f('ix_crime_type_name'), table_name='crime_type')
    op.drop_table('crime_type')
    # ### end Alembic commands ###
