import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { PageHeader } from "@/components/app/primitives";
import { listFIRs, getCasesMetadata, auditCaseExport } from "@/services/api";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { cn } from "@/lib/utils";
import { useAuthStore } from "@/stores/auth";
import { hasPermission, PERMISSIONS } from "@/lib/rbac";
import { MaskField, PermissionCard, RestrictedButton } from "@/components/rbac/permission";
import { ChevronDown, Download, Loader2 } from "lucide-react";
import { toast } from "sonner";

const STATUSES = ["Under Investigation", "Charge Sheeted", "Closed", "Undetected"] as const;

const DISTRICTS = [
  "Bengaluru Urban", "Bengaluru Rural", "Mysuru", "Mangaluru", "Belagavi",
  "Kalaburagi", "Hubballi-Dharwad", "Tumakuru", "Shivamogga", "Ballari",
  "Vijayapura", "Udupi", "Chitradurga", "Hassan",
];

export const Route = createFileRoute("/_app/cases/")({
  head: () => ({ meta: [{ title: "Case Search — Crime Intelligence Assistant" }] }),
  component: CasesPage,
});

function statusBadge(s: string) {
  switch (s) {
    case "Under Investigation":
      return "bg-info/15 text-info border-info/30";
    case "Charge Sheeted":
      return "bg-success/15 text-success border-success/30";
    case "Closed":
      return "bg-muted text-muted-foreground border-border";
    case "Undetected":
      return "bg-destructive/10 text-destructive border-destructive/30";
    default:
      return "bg-muted";
  }
}

function CasesPage() {
  const user = useAuthStore((s) => s.user);
  const canSeeSensitive = hasPermission(user, PERMISSIONS.SENSITIVE_CASE_ACCESS);
  const hideVictimColumn = user?.role === "POLICY_MAKER";

  const { data: metadata } = useQuery({
    queryKey: ["casesMetadata"],
    queryFn: getCasesMetadata,
    staleTime: Infinity,
  });

  const districtsList = metadata?.districts ?? DISTRICTS;
  const statusesList = metadata?.statuses ?? STATUSES;

  const districtOptions = user?.assignedDistricts?.length ? user.assignedDistricts : districtsList;
  const [q, setQ] = useState("");
  const [status, setStatus] = useState<string>("All");
  const [district, setDistrict] = useState<string>("All");
  const [page, setPage] = useState(1);
  const [isExporting, setIsExporting] = useState(false);

  const { data, isLoading } = useQuery({
    queryKey: ["firs", { q, status, district, page }],
    queryFn: () => listFIRs({ q, status, district, page, pageSize: 15 }),
  });

  const total = data?.total ?? 0;
  const totalPages = Math.max(1, Math.ceil(total / 15));

  const generateCSV = (items: any[]) => {
    const headers = ["Crime No.", "Case No.", "Date", "Victim/Complainant", "Station", "District", "Crime Head", "Status", "Gravity"];
    const rows = items.map((f) => [
      f.crimeNo,
      f.caseNo,
      f.date,
      (f as any).victimName ?? (f as any).complainant ?? "Victim record",
      f.station,
      f.district,
      f.crimeHead,
      f.status,
      f.gravity,
    ]);

    const csvContent =
      "data:text/csv;charset=utf-8,\uFEFF" +
      [headers.join(","), ...rows.map((e) => e.map(val => `"${String(val ?? '').replace(/"/g, '""')}"`).join(","))].join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `ksp_cases_export_${new Date().toISOString().split("T")[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const generatePDF = async (items: any[]) => {
    const { default: jsPDF } = await import("jspdf");
    const doc = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    // Add Header
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(16);
    doc.text("KARNATAKA STATE POLICE — SCRB INTELLIGENCE PLATFORM", 14, 20);
    
    doc.setFontSize(12);
    doc.text("CONFIDENTIAL CASE SEARCH EXPORT", 14, 26);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Generated By: ${user?.username || "Authorized Personnel"} (${user?.role || "SCRB Role"})`, 14, 32);
    doc.text(`Date: ${new Date().toLocaleString()}`, 14, 36);
    doc.text(`Total Records: ${items.length}`, 14, 40);

    // Draw table headers
    const startY = 48;
    const colWidths = [30, 25, 25, 40, 30, 30, 40, 30, 18]; // sum to ~268 (A4 Landscape usable width is 297 - 28 = 269)
    const headers = ["Crime No.", "Case No.", "Date", "Victim/Complainant", "Station", "District", "Crime Head", "Status", "Gravity"];
    
    let currentY = startY;

    // Draw header row background
    doc.setFillColor(240, 240, 240);
    doc.rect(14, currentY, 268, 8, "F");
    
    // Draw header text
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(8.5);
    let xOffset = 15;
    for (let i = 0; i < headers.length; i++) {
      doc.text(headers[i], xOffset, currentY + 5.5);
      xOffset += colWidths[i];
    }
    
    currentY += 8;

    // Draw data rows
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    
    items.forEach((item, index) => {
      // Check if we need to add a new page
      if (currentY > 185) {
        doc.addPage();
        currentY = 20;
        
        // Draw header row background on new page
        doc.setFillColor(240, 240, 240);
        doc.rect(14, currentY, 268, 8, "F");
        
        doc.setFont("Helvetica", "bold");
        let xOff = 15;
        for (let i = 0; i < headers.length; i++) {
          doc.text(headers[i], xOff, currentY + 5.5);
          xOff += colWidths[i];
        }
        currentY += 8;
        doc.setFont("Helvetica", "normal");
      }

      // Draw row background alternating colors
      if (index % 2 === 1) {
        doc.setFillColor(250, 250, 250);
        doc.rect(14, currentY, 268, 7, "F");
      }

      // Draw cell text
      const rowData = [
        item.crimeNo || "",
        item.caseNo || "",
        item.date || "",
        (item as any).victimName ?? (item as any).complainant ?? "Victim record",
        item.station || "",
        item.district || "",
        item.crimeHead || "",
        item.status || "",
        item.gravity || "",
      ];

      let cellX = 15;
      for (let i = 0; i < rowData.length; i++) {
        const text = String(rowData[i]);
        // Truncate long text if necessary
        const maxLen = i === 3 || i === 6 ? 24 : 18;
        const dispText = text.length > maxLen ? text.substring(0, maxLen) + ".." : text;
        doc.text(dispText, cellX, currentY + 5);
        cellX += colWidths[i];
      }

      currentY += 7;
    });

    // Save document
    doc.save(`ksp_cases_export_${new Date().toISOString().split("T")[0]}.pdf`);
  };

  const handleExport = async (format: "pdf" | "excel", scope: "current" | "all") => {
    setIsExporting(true);
    try {
      // 1. Audit the action first
      await auditCaseExport({ q, status, district, format });

      // 2. Retrieve the appropriate items
      let itemsToExport = [];
      if (scope === "current") {
        const res = await listFIRs({ q, status, district, page, pageSize: 15, bypass_masking: true });
        itemsToExport = res?.items ?? [];
      } else {
        const res = await listFIRs({ q, status, district, page: 1, pageSize: 5000, bypass_masking: true });
        itemsToExport = res?.items ?? [];
      }

      if (itemsToExport.length === 0) {
        toast.error("No cases to export");
        return;
      }

      // 3. Perform generation
      if (format === "excel") {
        generateCSV(itemsToExport);
      } else {
        await generatePDF(itemsToExport);
      }
      toast.success(`Successfully exported ${itemsToExport.length} cases.`);
    } catch (err) {
      console.error(err);
      toast.error("Export failed. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="p-6 max-w-[1600px] mx-auto">
      <PageHeader
        title="Case Search"
        subtitle={`${total.toLocaleString()} FIRs indexed - scoped to ${user?.assignedDistricts?.length ? user.assignedDistricts.join(", ") : "authorized Karnataka districts"}.`}
        actions={
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <RestrictedButton size="sm" variant="outline" permissions={[PERMISSIONS.EXPORT_REPORTS]} className="flex items-center gap-1">
                {isExporting ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Download className="h-4 w-4" />
                )}
                Export
                <ChevronDown className="h-3 w-3 opacity-60" />
              </RestrictedButton>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end" className="w-56">
              <DropdownMenuItem onClick={() => handleExport("pdf", "current")} disabled={isExporting}>
                Export Current Page (PDF)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport("excel", "current")} disabled={isExporting}>
                Export Current Page (Excel)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport("pdf", "all")} disabled={isExporting}>
                Export All Filtered (PDF)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => handleExport("excel", "all")} disabled={isExporting}>
                Export All Filtered (Excel)
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        }
      />

      <div className="flex flex-wrap items-end gap-3 mb-4">
        <div className="flex-1 min-w-64">
          <Input
            placeholder="Search Crime No, station, district, complainant…"
            value={q}
            onChange={(e) => {
              setQ(e.target.value);
              setPage(1);
            }}
          />
        </div>
        <div className="w-48">
          <Select
            value={status}
            onValueChange={(v) => {
              setStatus(v);
              setPage(1);
            }}
          >
            <SelectTrigger>
              <SelectValue placeholder="Status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="All">All statuses</SelectItem>
              {statusesList.map((s) => (
                <SelectItem key={s} value={s}>
                  {s}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div className="w-56">
          <Select
            value={district}
            onValueChange={(v) => {
              setDistrict(v);
              setPage(1);
            }}
          >
            <SelectTrigger>
              <SelectValue placeholder="District" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="All">All districts</SelectItem>
              {districtOptions.map((d) => (
                <SelectItem key={d} value={d}>
                  {d}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>

      <div className="rounded-xl glass overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-xs">
            <thead className="bg-muted/60 border-b border-border">
              <tr>
                <th className="text-left px-3 py-2 font-medium">Crime No.</th>
                <th className="text-left px-3 py-2 font-medium">Case No.</th>
                <th className="text-left px-3 py-2 font-medium">Date</th>
                {!hideVictimColumn && <th className="text-left px-3 py-2 font-medium">Victim</th>}
                <th className="text-left px-3 py-2 font-medium">Station</th>
                <th className="text-left px-3 py-2 font-medium">District</th>
                <th className="text-left px-3 py-2 font-medium">Crime Head</th>
                <th className="text-left px-3 py-2 font-medium">Status</th>
                <th className="text-left px-3 py-2 font-medium">Gravity</th>
              </tr>
            </thead>
            <tbody>
              {isLoading &&
                Array.from({ length: 8 }).map((_, i) => (
                  <tr key={i} className="border-b border-border">
                    <td colSpan={hideVictimColumn ? 8 : 9} className="p-2">
                      <Skeleton className="h-6" />
                    </td>
                  </tr>
                ))}
              {!isLoading && data?.items.length === 0 && (
                <tr>
                  <td colSpan={hideVictimColumn ? 8 : 9} className="p-8">
                    <PermissionCard
                      moduleName="Assigned Investigations"
                      reason={q || status !== "All" || district !== "All" ? "No assigned investigations match the current filters." : "You currently have no assigned investigations in your permitted scope."}
                      className="mx-auto max-w-xl text-left"
                    />
                  </td>
                </tr>
              )}
              {data?.items.map((f) => (
                <tr key={f.id} className="border-b border-border hover:bg-accent/40 cursor-pointer">
                  <td className="px-3 py-2">
                    <Link
                      to="/cases/$firId"
                      params={{ firId: f.id }}
                      className="font-mono text-primary hover:underline"
                    >
                      {f.crimeNo}
                    </Link>
                  </td>
                  <td className="px-3 py-2 font-mono text-[11px]">{f.caseNo}</td>
                  <td className="px-3 py-2 whitespace-nowrap">{f.date}</td>
                  {!hideVictimColumn && (
                    <td className="px-3 py-2">
                      <MaskField
                        value={(f as any).victimName ?? (f as any).complainant ?? "Victim record"}
                        permission={PERMISSIONS.SENSITIVE_CASE_ACCESS}
                        kind="name"
                      />
                      {!canSeeSensitive && (
                        <span className="ml-2 text-[10px] text-muted-foreground">masked</span>
                      )}
                    </td>
                  )}
                  <td className="px-3 py-2">{f.station}</td>
                  <td className="px-3 py-2">{f.district}</td>
                  <td className="px-3 py-2">{f.crimeHead}</td>
                  <td className="px-3 py-2">
                    <Badge
                      variant="outline"
                      className={cn("border font-medium", statusBadge(f.status))}
                    >
                      {f.status}
                    </Badge>
                  </td>
                  <td className="px-3 py-2">{f.gravity}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex items-center justify-between px-3 py-2 border-t border-border text-xs text-muted-foreground">
          <span>
            Page {page} of {totalPages}
          </span>
          <div className="flex gap-1">
            <Button
              size="sm"
              variant="outline"
              disabled={page === 1}
              onClick={() => setPage((p) => p - 1)}
            >
              Prev
            </Button>
            <Button
              size="sm"
              variant="outline"
              disabled={page >= totalPages}
              onClick={() => setPage((p) => p + 1)}
            >
              Next
            </Button>
          </div>
        </div>
      </div>
    </div>
  );
}
