"""update_audit_log_fields

Revision ID: 794251b8bd91
Revises: eef6612eca82
Create Date: 2026-07-19 16:32:13.149206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794251b8bd91'
down_revision: Union[str, None] = 'eef6612eca82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('action', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('target_user_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('district_id', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('case_id', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_log', sa.Column('user_agent', sa.String(length=255), nullable=True))
    op.alter_column('audit_log', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_district_id'), 'audit_log', ['district_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_district_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.alter_column('audit_log', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('audit_log', 'user_agent')
    op.drop_column('audit_log', 'reason')
    op.drop_column('audit_log', 'case_id')
    op.drop_column('audit_log', 'district_id')
    op.drop_column('audit_log', 'supervisor_id')
    op.drop_column('audit_log', 'target_user_id')
    op.drop_column('audit_log', 'action')
    # ### end Alembic commands ###
