"""add_complainant_and_demographics

Revision ID: 79ffdf1de603
Revises: bce696f395ce
Create Date: 2026-07-20 21:44:18.559678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79ffdf1de603'
down_revision: Union[str, None] = 'bce696f395ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caste_master',
    sa.Column('caste_master_id', sa.Integer(), nullable=False),
    sa.Column('caste_master_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('caste_master_id')
    )
    op.create_index(op.f('ix_caste_master_caste_master_name'), 'caste_master', ['caste_master_name'], unique=False)
    op.create_table('occupation_master',
    sa.Column('occupation_id', sa.Integer(), nullable=False),
    sa.Column('occupation_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('occupation_id')
    )
    op.create_index(op.f('ix_occupation_master_occupation_name'), 'occupation_master', ['occupation_name'], unique=False)
    op.create_table('religion_master',
    sa.Column('religion_id', sa.Integer(), nullable=False),
    sa.Column('religion_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('religion_id')
    )
    op.create_index(op.f('ix_religion_master_religion_name'), 'religion_master', ['religion_name'], unique=False)
    op.create_table('complainant_details',
    sa.Column('complainant_id', sa.Integer(), nullable=False),
    sa.Column('case_master_id', sa.Integer(), nullable=False),
    sa.Column('complainant_name', sa.String(length=255), nullable=False),
    sa.Column('age_year', sa.Integer(), nullable=True),
    sa.Column('gender_id', sa.Integer(), nullable=True),
    sa.Column('occupation_id', sa.Integer(), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.Column('caste_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['case_master_id'], ['case_master.case_master_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['caste_id'], ['caste_master.caste_master_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupation_master.occupation_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['religion_id'], ['religion_master.religion_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('complainant_id')
    )
    op.create_index(op.f('ix_complainant_details_case_master_id'), 'complainant_details', ['case_master_id'], unique=False)
    op.create_index(op.f('ix_complainant_details_caste_id'), 'complainant_details', ['caste_id'], unique=False)
    op.create_index(op.f('ix_complainant_details_complainant_name'), 'complainant_details', ['complainant_name'], unique=False)
    op.create_index(op.f('ix_complainant_details_occupation_id'), 'complainant_details', ['occupation_id'], unique=False)
    op.create_index(op.f('ix_complainant_details_religion_id'), 'complainant_details', ['religion_id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'employee_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index(op.f('ix_complainant_details_religion_id'), table_name='complainant_details')
    op.drop_index(op.f('ix_complainant_details_occupation_id'), table_name='complainant_details')
    op.drop_index(op.f('ix_complainant_details_complainant_name'), table_name='complainant_details')
    op.drop_index(op.f('ix_complainant_details_caste_id'), table_name='complainant_details')
    op.drop_index(op.f('ix_complainant_details_case_master_id'), table_name='complainant_details')
    op.drop_table('complainant_details')
    op.drop_index(op.f('ix_religion_master_religion_name'), table_name='religion_master')
    op.drop_table('religion_master')
    op.drop_index(op.f('ix_occupation_master_occupation_name'), table_name='occupation_master')
    op.drop_table('occupation_master')
    op.drop_index(op.f('ix_caste_master_caste_master_name'), table_name='caste_master')
    op.drop_table('caste_master')
    # ### end Alembic commands ###
