"""sync audit log schema

Revision ID: bdd49e5b4fd8
Revises: 79ffdf1de603
Create Date: 2026-07-23 13:52:09.483249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdd49e5b4fd8'
down_revision: Union[str, None] = '79ffdf1de603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('role', sa.String(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('api', sa.String(length=255), nullable=True))
    op.add_column('audit_log', sa.Column('response_size', sa.Integer(), nullable=True))
    op.add_column('audit_log', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_log', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'status')
    op.drop_column('audit_log', 'ip_address')
    op.drop_column('audit_log', 'response_size')
    op.drop_column('audit_log', 'api')
    op.drop_column('audit_log', 'role')
    op.drop_column('audit_log', 'username')
    # ### end Alembic commands ###
