"""add_abac_models

Revision ID: eef6612eca82
Revises: 83015d4be814
Create Date: 2026-07-19 16:31:46.511592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eef6612eca82'
down_revision: Union[str, None] = '83015d4be814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_district_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('removed_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['removed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_district_assignments_district'), 'user_district_assignments', ['district'], unique=False)
    op.create_index(op.f('ix_user_district_assignments_user_id'), 'user_district_assignments', ['user_id'], unique=False)
    op.create_index('uq_active_user_district', 'user_district_assignments', ['user_id', 'district'], unique=True, postgresql_where=sa.text('is_active = TRUE'))
    op.create_table('district_access_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('requested_district', sa.String(length=100), nullable=False),
    sa.Column('related_case_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['related_case_id'], ['case_master.case_master_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_district_access_requests_related_case_id'), 'district_access_requests', ['related_case_id'], unique=False)
    op.create_index(op.f('ix_district_access_requests_requested_district'), 'district_access_requests', ['requested_district'], unique=False)
    op.create_index(op.f('ix_district_access_requests_requester_id'), 'district_access_requests', ['requester_id'], unique=False)
    op.create_index(op.f('ix_district_access_requests_status'), 'district_access_requests', ['status'], unique=False)
    op.create_table('temporary_district_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('access_request_id', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('related_case_id', sa.Integer(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['access_request_id'], ['district_access_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_case_id'], ['case_master.case_master_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_district_permissions_access_request_id'), 'temporary_district_permissions', ['access_request_id'], unique=False)
    op.create_index(op.f('ix_temporary_district_permissions_approved_by'), 'temporary_district_permissions', ['approved_by'], unique=False)
    op.create_index(op.f('ix_temporary_district_permissions_district'), 'temporary_district_permissions', ['district'], unique=False)
    op.create_index(op.f('ix_temporary_district_permissions_expires_at'), 'temporary_district_permissions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_temporary_district_permissions_is_revoked'), 'temporary_district_permissions', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_temporary_district_permissions_user_id'), 'temporary_district_permissions', ['user_id'], unique=False)
    
    # Check if investigation_history table exists before doing index operations or table creation
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'investigation_history' not in tables:
        op.create_table(
            'investigation_history',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('timestamp', sa.DateTime(), nullable=False),
            sa.Column('investigation_name', sa.String(length=255), nullable=False),
            sa.Column('entity_type', sa.String(length=50), nullable=False),
            sa.Column('entity_id', sa.String(length=100), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_investigation_history_user_id'), 'investigation_history', ['user_id'], unique=False)
    else:
        # Check if the new index already exists
        indexes = [idx['name'] for idx in inspector.get_indexes('investigation_history')]
        if 'ix_investigation_history_user_id' not in indexes:
            op.execute("DROP INDEX IF EXISTS idx_investigation_history_user_id")
            op.create_index(op.f('ix_investigation_history_user_id'), 'investigation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'investigation_history' in tables:
        indexes = [idx['name'] for idx in inspector.get_indexes('investigation_history')]
        if 'ix_investigation_history_user_id' in indexes:
            op.drop_index(op.f('ix_investigation_history_user_id'), table_name='investigation_history')
        if 'idx_investigation_history_user_id' not in indexes:
            op.create_index('idx_investigation_history_user_id', 'investigation_history', ['user_id'], unique=False)
    op.drop_index(op.f('ix_temporary_district_permissions_user_id'), table_name='temporary_district_permissions')
    op.drop_index(op.f('ix_temporary_district_permissions_is_revoked'), table_name='temporary_district_permissions')
    op.drop_index(op.f('ix_temporary_district_permissions_expires_at'), table_name='temporary_district_permissions')
    op.drop_index(op.f('ix_temporary_district_permissions_district'), table_name='temporary_district_permissions')
    op.drop_index(op.f('ix_temporary_district_permissions_approved_by'), table_name='temporary_district_permissions')
    op.drop_index(op.f('ix_temporary_district_permissions_access_request_id'), table_name='temporary_district_permissions')
    op.drop_table('temporary_district_permissions')
    op.drop_index(op.f('ix_district_access_requests_status'), table_name='district_access_requests')
    op.drop_index(op.f('ix_district_access_requests_requester_id'), table_name='district_access_requests')
    op.drop_index(op.f('ix_district_access_requests_requested_district'), table_name='district_access_requests')
    op.drop_index(op.f('ix_district_access_requests_related_case_id'), table_name='district_access_requests')
    op.drop_table('district_access_requests')
    op.drop_index('uq_active_user_district', table_name='user_district_assignments', postgresql_where=sa.text('is_active = TRUE'))
    op.drop_index(op.f('ix_user_district_assignments_user_id'), table_name='user_district_assignments')
    op.drop_index(op.f('ix_user_district_assignments_district'), table_name='user_district_assignments')
    op.drop_table('user_district_assignments')
    # ### end Alembic commands ###
